### PR TITLE
Avoid loading keys from corrupted entries [JIRA: RIAK-1925]

### PR DESCRIPTION
**Pull request by engelsanchez**
Due to an optimization added last year, when keys are loaded from a data
file due to a bad or missing hintfile, keys were loaded even if the
record did not pass the CRC test. This was done to avoid extra I/O by
skipping reading the value, but it is incorrect and has caused a few
customers some problems either by Bitcask crashing on startup or data
scans failing later when hitting a corrupt key.

This is the main part of the fix for https://github.com/basho/bitcask/issues/212. 
There will be another PR to prevent keys with an unknown format from crashing folding

### CODE REVIEW

**Comment by mrallen1** [comment]
Just wanted to note I haven't had a chance to look at this in detail but I will tackle it 1st thing tomorrow.

**Comment by engelsanchez** [comment]
I should clarify that the optimization I mentioned from last year did not introduce the CRC check skipping. In fact, that was done just the same before that.  So loading from data files when a hintfile was invalid could always load keys from corrupted records.

**Comment by mrallen1** [comment]
This all looks good. Tests pass and dialyzer's clean after the last commit. :+1:

**Comment by mrallen1** [comment]
:+1: e7bb7c8

**Comment by engelsanchez** [comment]
@borshop merge

**Comment by DSomogyi** [comment]
create jira issue

**Pull request merged**
