### PR TITLE
Bump cuttlefish version to 2.0.6

### PR DESCRIPTION
**Pull request by nickelization**

### CODE REVIEW

**Comment by nickelization** [comment]
@borshop merge

**Comment by javajolt** [comment]
@nickelization Will this update get a tag in bitcask or simply live on a branch?

**Comment by nickelization** [comment]
@javajolt I'm planning to push a 1.7.4 tag, I've just been putting it off because I'm still untangling some other dependency-related problems. Sounds good?

**Comment by javajolt** [comment]
@nickelization Thanks.  If you can just let me know when you do, it will help with some TS dependency foo I'm working on.

**Pull request merged**
